/* Pin constants */

#define LEFT_INDICATOR_LIGHT_PIN GPIO_PIN12
#define RIGHT_INDICATOR_LIGHT_PIN GPIO_PIN21
#define BRAKE_LIGHT_PIN GPIO_PIN20
#define LEFT_INDICATOR_BUTTON_PIN GPIO_PIN13
#define RIGHT_INDICATOR_BUTTON_PIN GPIO_PIN26
#define CHANGE_MODE_BUTTON_PIN GPIO_PIN19
#define HALL_PIN GPIO_PIN4
#define SDA GPIO_PIN2
#define SCL GPIO_PIN3
#define VDD GPIO_PIN6
