/* Pin constants */

#define LEFT_INDICATOR_LIGHT_PIN GPIO_PIN6
#define RIGHT_INDICATOR_LIGHT_PIN GPIO_PIN7
#define BRAKE_LIGHT_PIN GPIO_PIN8
#define LEFT_INDICATOR_BUTTON_PIN GPIO_PIN16
#define RIGHT_INDICATOR_BUTTON_PIN GPIO_PIN17
#define CHANGE_MODE_BUTTON_PIN GPIO_PIN18
#define HALL_PIN GPIO_PIN4
#define SDA GPIO_PIN2
#define SCL GPIO_PIN3
#define VDD GPIO_PIN5
#define SEGMENT_GPIO_START GPIO_PIN10
#define SEGMENT_GPIO_END GPIO_PIN13
#define DIGIT_GPIO_START GPIO_PIN20
#define DIGIT_GPIO_END GPIO_PIN27