/* Pin constants */

#define LEFT_INDICATOR_LIGHT_PIN GPIO_PIN12
#define RIGHT_INDICATOR_LIGHT_PIN GPIO_PIN21
#define BRAKE_LIGHT_PIN GPIO_PIN20
#define LEFT_INDICATOR_BUTTON_PIN GPIO_PIN13
#define RIGHT_INDICATOR_BUTTON_PIN GPIO_PIN26
#define CHANGE_MODE_BUTTON_PIN GPIO_PIN19
